# Don't Forget Set Environment Variables Before Run This yml file
# APP_ENV=development || production
version: '2'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx.${APP_ENV}.dockerfile
    depends_on:
      - blogs
    ports:
      - '80:80'
      - '443:443'
    networks:
      - blogs-network

  blogs:
    container_name: nodejs-blogs
    build:
      context: .
      dockerfile: ./docker/node.${APP_ENV}.dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/var/www/blogs
    depends_on:
      - 'postgres'
    networks:
      - blogs-network

  postgres:
    image: 'postgres'
    env_file:
      - ./docker/env/postgres.${APP_ENV}.env
      - ./docker/env/app.${APP_ENV}.env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - blogs-network

volumes:
  pgdata:

networks:
  blogs-network:
    driver: bridge
