FROM node:latest

LABEL author="Eslam Elkholy"

WORKDIR /var/www/blogs

RUN mkdir -p /var/www/blogs && chown -f root:root /var/www/blogs
COPY --chown=root:root . /var/www/blogs

RUN npm install


EXPOSE 3000

ENTRYPOINT ["/bin/bash", "./docker/scripts/node.development.sh"]
